palette = "everforest_light_medium"

add_newline = true
command_timeout = 1000

format = """
$character\
\
[â–ˆ](fg:bg2 bg:black)\
$directory\
[â–ˆî‚¼](fg:bg2 bg:background)\
$git_branch\
$git_status\
$package\
$cmd_duration\
$line_break\
[ï²  ](fg:fg bg:background)\
[â€]()"""

[character]
format = "$symbol"
error_symbol = "[â–ˆ](fg:red bg:bg0)[ï‹“ ERROR](fg:red bg:bg0 inverted bold)[î‚¼](fg:red bg:halfway_red)[î‚¼](fg:halfway_red bg:bg2)"
success_symbol = "[â–ˆ](fg:green bg:bg0)[î• PROMPT](fg:green bg:bg0 inverted bold)[î‚¼](fg:green bg:halfway)[î‚¼](fg:halfway bg:bg2)"
vimcmd_symbol = "[â–ˆ](fg:green bg:bg0)[î• NORMAL](fg:green bg:bg0 inverted bold)[î‚¼](fg:green bg:halfway)[î‚¼](fg:halfway bg:bg2)"

[fill]
symbol = ' '
style = 'bg:background'

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format="[ ó°Œ $duration ]($style)"
style="bold fg:cyan bg:background"

[directory]
truncation_length = 5
format = "[ó°‰‹ $path]($style)[$lock_symbol]($lock_style)"
style = "bold fg:fg bg:bg2"
read_only = "ğŸ”’"
read_only_style= "bold white"

[username]
show_always = true
style_user = "bg:bright-black"
style_root = "bg:bright-black"
format = '[ $user ]($style)'

[hostname]
format = "[ $hostname ]($style)"
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "fg:green bg:bright-black"

[git_commit]
commit_hash_length = 8
style = "bold white"

[status]
style = "bg:background"
symbol = "ğŸ’¥ "
format = '($style)'
disabled = false

[git_branch]
format = "[ ó°˜¬ $branch ]($style)"
style = "bold bg:background fg:purple"

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold bg:background fg:fg"

[package]
format = '[$version](208 bold) '


[palettes.everforest_light_medium]
bg0 = "#fdf6e3"
bg1 = "#f4f0d9"
bg2 = "#efebd4"
bg3 = "#e6e2cc"
bg4 = "#e0dcc7"
bg5 = "#bdc3af"
fg = "#5c6a72"
grey0 = "#a6b0a0"
grey1 = "#939f91"
grey2 = "#829181"
red = "#f85552"
orange = "#f57d26"
yellow = "#dfa000"
green = "#8da101"
cyan = "#35a77c"
blue = "#3a94c5"
purple = "#df69ba"
red_dim = "#e67e80"
orange_dim = "#e69875"
yellow_dim = "#dbbc7f"
green_dim = "#a7c080"
cyan_dim = "#83c092"
blue_dim = "#7fbbb3"
purple_dim = "#d699b6"
bg_green = "#f0f1d2"
background = "#fffbef"
halfway = "#c1c96d"
halfway_red = "#f6a295"
none = "NONE"
